format             = """
[â•­â”€](fg:surface2 bold)\
$os\
[î‚°](fg:flamingo bg:mauve)\
$directory\
[î‚°](fg:mauve bg:maroon)\
($git_branch\
$git_status\
$git_commit\
[ ](bg:maroon))\
[î‚°](fg:maroon bg:yellow)\
($c\
$python\
$rust\
$golang\
$nodejs\
$kotlin\
$java\
$php\
$haskell\
[ ](bg:yellow))\
[î‚°](fg:yellow bg:teal)\
($conda\
$docker_context\
[ ](bg:teal))\
[î‚°](fg:teal)\
$fill\
[î‚²](fg:peach)\
$status\
[î‚²](fg:red bg:peach)\
$cmd_duration\
[î‚²](fg:pink bg:red)\
$username\
$hostname\
[î‚²](fg:rosewater bg:pink)\
$time\
[â”€â•®](fg:surface2 bold)\
$line_break\
[â•°â”€](fg:surface2 bold)\
$character\
"""
right_format       = """
[â”€â•¯](fg:surface2 bold)\
"""
palette            = "catppuccin_mocha"

[palettes.catppuccin_mocha]
rosewater          = "#f5e0dc"
flamingo           = "#f2cdcd"
pink               = "#f5c2e7"
mauve              = "#cba6f7"
red                = "#f38ba8"
maroon             = "#eba0ac"
peach              = "#fab387"
yellow             = "#f9e2af"
green              = "#a6e3a1"
teal               = "#94e2d5"
sky                = "#89dceb"
sapphire           = "#74c7ec"
blue               = "#89b4fa"
lavender           = "#b4befe"
text               = "#cdd6f4"
subtext1           = "#bac2de"
subtext0           = "#a6adc8"
overlay2           = "#9399b2"
overlay1           = "#7f849c"
overlay0           = "#6c7086"
surface2           = "#585b70"
surface1           = "#45475a"
surface0           = "#313244"
base               = "#1e1e2e"
mantle             = "#181825"
crust              = "#11111b"

[os]
style              = "fg:crust bg:flamingo"
format             = "[ $symbol ]($style)"
disabled           = false

[os.symbols]
AIX                = "AIX"
Alpaquita          = "\uf26a" # "\uf26a" "ï‰ª" "\ue3a5\ue390" "î¥î"
AlmaLinux          = "\uf31d" # "ïŒ"
Alpine             = "\uf300" # "ïŒ€"
Amazon             = "\uf270" # "ï‰°"
Android            = "\ue70e" # "îœ"
Arch               = "\uf303" # "ïŒƒ"
Artix              = "\uf31f" # "ïŒŸ"
CentOS             = "\uf304" # "ïŒ„"
Debian             = "\uf306" # "ïŒ†"
DragonFly          = "\ueef8" # "î»¸" "î†" "ğŸ‰"
Emscripten         = "\u26A1" # "âš¡"
EndeavourOS        = "\uf322" # "ïŒ¢" "ï†—"
Fedora             = "\uf30a" # "ïŒŠ"
FreeBSD            = "\uf30c" # "ïŒŒ"
Garuda             = "\uf337" # "ïŒ·"
Gentoo             = "\uf30d" # "ïŒ"
HardenedBSD        = "\uf132" # "ï„²"
Illumos            = "\uf326" # "ğŸ¦"
Kali               = "\uf327" # "ïŒ§"
Linux              = "\uf17c" # "ï…¼"
Mabox              = "\uf1b2" # "ï†²" "ğŸ“¦"
Macos              = "\uf302" # "ïŒ‚"
Manjaro            = "\uf312" # "ïŒ’"
Mariner            = "\ue7ae" # "\ue7ae" "î®"
MidnightBSD        = "\ue3e0" # "ğŸŒ˜"
Mint               = "\uf30e" # "ïŒ"
NetBSD             = "\u2691" # "âš‘"
NixOS              = "\uf313" # "ïŒ“"
OpenBSD            = "\uf328" # "ïŒ¨"
OpenCloudOS        = "\uf0c2" # "ïƒ‚"
openEuler          = "\u2208" # "\u2208" "âˆˆ"
openSUSE           = "\uf314" # "ïŒ”"
OracleLinux        = "\u213A" # "\u213A" "â„º" "âŠ‚âŠƒ" "\u2282\u2283"
Pop                = "\uf32a" # "ïŒª"
Raspbian           = "\uf315" # "ïŒ•"
Redhat             = "\uf316" # "ïŒ–" "ó±„›"
RedHatEnterprise   = "\uf316" # "ïŒ–" "ó±„›"
RockyLinux         = "\uf32b" # "ïŒ«"
Redox              = "\uf331" # "ïŒ±" "ó°º•"
Solus              = "\uf32d" # "ïŒ­" "ï…¼"
SUSE               = "\uef6d" # "ïŒ”"
Ubuntu             = "\uf31b" # "ïŒ›"
Ultramarine        = "ó±™³"      # "ğŸ”·"
Unknown            = "\uf108" # "ï„ˆ"
Void               = "\uf32e" # "ïŒ®" "îŠ™"
Windows            = "\uf17a" # "îœ"

[directory]
read_only          = "ğŸ”’"
read_only_style    = "fg:crust bg:mauve"
style              = "fg:crust bg:mauve"
format             = "[ ï¼ $path ]($style)[$read_only]($read_only_style)"
truncation_length  = 0
truncate_to_repo   = false

[git_branch]
symbol             = "ï˜"
style              = "fg:crust bg:maroon"
format             = "[ $symbol $branch]($style)"

[git_status]
style              = "fg:crust bg:maroon"
ahead              = "â‡¡$count"
behind             = "â‡£$count"
conflicted         = "=$count"
deleted            = "âœ˜$count"
modified           = "!$count"
renamed            = "Â»$count"
staged             = "+$count"
stashed            = "\\$$count"
untracked          = "?$count"
format             = "[( $all_status$ahead_behind)]($style)"

[git_commit]
tag_symbol         = "ï’ " # "\uf412" "ï’" "ï€«"
style              = "fg:crust bg:maroon"
format             = "[ ($tag )$hash]($style)"
commit_hash_length = 8
disabled           = false
tag_disabled       = false

[c]
symbol             = "î˜"
style              = "fg:crust bg:yellow"
format             = "[ $symbol( $version)]($style)"

[golang]
symbol             = "î˜§"
style              = "fg:crust bg:yellow"
format             = "[ $symbol( $version)]($style)"

[haskell]
symbol             = "î˜Ÿ"
style              = "fg:crust bg:yellow"
format             = "[ $symbol( $version)]($style)"

[java]
symbol             = "î‰–"
style              = "fg:crust bg:yellow"
format             = "[ $symbol( $version)]($style)"

[kotlin]
symbol             = "î˜´"
style              = "fg:crust bg:yellow"
format             = "[ $symbol( $version)]($style)"

[nodejs]
symbol             = "îœ˜"
style              = "fg:crust bg:yellow"
format             = "[ $symbol( $version)]($style)"

[php]
symbol             = "î˜ˆ"
style              = "fg:crust bg:yellow"
format             = "[ $symbol( $version)]($style)"

[python]
symbol             = "î˜†"
style              = "fg:crust bg:yellow"
format             = '[ $symbol( $version)( \(#$virtualenv\))]($style)'

[rust]
symbol             = "î¨"
style              = "fg:crust bg:yellow"
format             = "[ $symbol( $version)]($style)"

[conda]
symbol             = "ï„Œ"
style              = "fg:crust bg:teal"
format             = "[ $symbol $environment]($style)"
ignore_base        = false

[docker_context]
symbol             = "ïŒˆ"
style              = "fg:crust bg:teal"
format             = "[ $symbol( $context)]($style)"

[fill]
symbol             = "â”€"
style              = "surface2 bold"

[status]
map_symbol         = false
symbol             = " âœ˜" # "\u2717" "\uf467" "\uebde" "î¯" "âœ˜"
success_symbol     = ""        # "âœ”"
style              = "fg:crust bg:peach"
format             = "[$symbol $status( \uf0a2 $signal_number-$signal_name) ]($style)" # "\uf0a2" "ï–›" "\ueaa2"
disabled           = false

[cmd_duration]
style              = "fg:crust bg:red"
format             = "[ ï‰’ $duration ]($style)"
show_milliseconds  = true
show_notifications = true
min_time_to_notify = 45000
disabled           = false

[username]
style_root         = "fg:crust bg:pink bold"
style_user         = "fg:crust bg:pink"
format             = "[ $user]($style)"
show_always        = true

[hostname]
style              = "fg:crust bg:pink"
format             = "[@$hostname ]($style)"
ssh_only           = false
# ssh_symbol       = "@" # "\ue36e" "î®" "ï…½â‡’" "ï£· " "ï¬â‡’"
disabled           = false

[time]
style              = "fg:crust bg:rosewater"
format             = "[ ï€— $time ]($style)"
disabled           = false # set to "false", if you want to see the time

[character]
success_symbol            = "[â¯](fg:green bold)"
error_symbol              = "[â¯](fg:red bold)"
vimcmd_symbol             = "[â®](fg:green bold)"
vimcmd_replace_one_symbol = "[â®](fg:lavender bold)"
vimcmd_replace_symbol     = "[â®](fg:lavender bold)"
vimcmd_visual_symbol      = "[â®](fg:yellow) bold"
disabled                  = false
