# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[[mgr.prepend_keymap]]
on   = "l"
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on   = "p"
run  = "plugin smart-paste"
desc = "Paste into the hovered directory or CWD"

[[mgr.prepend_keymap]]
on   = [ "g", "r" ]
run  = 'shell -- ya emit cd "$(git rev-parse --show-toplevel)"'
desc = "Go git root directory"

# [[mgr.prepend_keymap]]
# on   = "y"
# run  = [ 'shell -- echo "$@" | xclip -i -selection clipboard -t text/uri-list', "yank" ]
# desc = "Copy yanked path to system clipboard on x11"

# [[mgr.prepend_keymap]]
# on   = "y"
# run  = [ 'shell -- for path in "$@"; do echo "file://$path"; done | wl-copy -t text/uri-list', "yank" ]
# desc = "Copy yanked path to system clipboard on wayland"

[[mgr.prepend_keymap]]
on   = "y"
run  = [ 'shell -- for path in "$@"; do echo "$path"; done | pbcopy', "yank" ]
desc = "Copy yanked path to system clipboard on macos"

[[mgr.prepend_keymap]]
on   = ["C"]
run  = "plugin ouch"
desc = "Compress with ouch"

[[mgr.prepend_keymap]]
on   = [ "b", "s" ]
run  = "plugin bookmarks save"
desc = "Save current position as a bookmark"

[[mgr.prepend_keymap]]
on   = [ "b", "j" ]
run  = "plugin bookmarks jump"
desc = "Jump to a bookmark"

[[mgr.prepend_keymap]]
on   = [ "b", "d" ]
run  = "plugin bookmarks delete"
desc = "Delete a bookmark"

[[mgr.prepend_keymap]]
on   = [ "b", "D" ]
run  = "plugin bookmarks delete_all"
desc = "Delete all bookmarks"

[[input.prepend_keymap]]
on   = "<Esc>"
run  = "close"
desc = "Cancel input"
